/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskSplitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTask"
      | "cancelTask"
      | "claimReward"
      | "claimTask"
      | "createProject"
      | "flagSubmission"
      | "getContributorPoints"
      | "getLeaderboard"
      | "getProject"
      | "getProjectCounter"
      | "getProjectedReward"
      | "getTask"
      | "globalEarnings"
      | "projects"
      | "resolveDispute"
      | "rewardEarners"
      | "submitTask"
      | "verifyTask"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "ProjectCreated"
      | "RewardClaimed"
      | "TaskAdded"
      | "TaskCancelled"
      | "TaskClaimed"
      | "TaskFlagged"
      | "TaskSubmitted"
      | "TaskVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTask",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flagSubmission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorPoints",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectedReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEarners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTask",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTask",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "globalEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardEarners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyTask", data: BytesLike): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    approved: boolean,
    resolver: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    approved: boolean,
    resolver: string
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    approved: boolean;
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    name: string,
    sponsor: AddressLike,
    rewardPool: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    name: string,
    sponsor: string,
    rewardPool: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    name: string;
    sponsor: string;
    rewardPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    contributor: string,
    amount: bigint,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    contributor: string;
    amount: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAddedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    description: string,
    pointValue: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    description: string,
    pointValue: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    description: string;
    pointValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    claimant: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    claimant: string
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    claimant: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    claimant: string,
    deadline: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    claimant: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskFlaggedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    flagger: AddressLike,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    flagger: string,
    stake: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    flagger: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSubmittedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    contributor: AddressLike,
    proofUrl: string,
    challengePeriodEnd: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    contributor: string,
    proofUrl: string,
    challengePeriodEnd: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    contributor: string;
    proofUrl: string;
    challengePeriodEnd: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskVerifiedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    contributor: AddressLike,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    contributor: string,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    contributor: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskSplit extends BaseContract {
  connect(runner?: ContractRunner | null): TaskSplit;
  waitForDeployment(): Promise<this>;

  interface: TaskSplitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTask: TypedContractMethod<
    [projectId: BigNumberish, description: string, points: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimReward: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProject: TypedContractMethod<
    [name: string, durationDays: BigNumberish],
    [bigint],
    "payable"
  >;

  flagSubmission: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "payable"
  >;

  getContributorPoints: TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [],
    [[string[], bigint[]] & { earners: string[]; earnings: bigint[] }],
    "view"
  >;

  getProject: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        name: string;
        sponsor: string;
        rewardPool: bigint;
        totalVerifiedPoints: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;

  getProjectCounter: TypedContractMethod<[], [bigint], "view">;

  getProjectedReward: TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;

  getTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, boolean] & {
        description: string;
        pointValue: bigint;
        claimDeadline: bigint;
        status: bigint;
        claimant: string;
        proofUrl: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  globalEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        sponsor: string;
        rewardPool: bigint;
        initialRewardPool: bigint;
        totalVerifiedPoints: bigint;
        endTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  resolveDispute: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, approveWork: boolean],
    [void],
    "nonpayable"
  >;

  rewardEarners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  submitTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, proofUrl: string],
    [void],
    "nonpayable"
  >;

  verifyTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, description: string, points: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [name: string, durationDays: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "flagSubmission"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getContributorPoints"
  ): TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { earners: string[]; earnings: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        name: string;
        sponsor: string;
        rewardPool: bigint;
        totalVerifiedPoints: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectedReward"
  ): TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, boolean] & {
        description: string;
        pointValue: bigint;
        claimDeadline: bigint;
        status: bigint;
        claimant: string;
        proofUrl: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        sponsor: string;
        rewardPool: bigint;
        initialRewardPool: bigint;
        totalVerifiedPoints: bigint;
        endTime: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, approveWork: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardEarners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "submitTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, proofUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAdded"
  ): TypedContractEvent<
    TaskAddedEvent.InputTuple,
    TaskAddedEvent.OutputTuple,
    TaskAddedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskFlagged"
  ): TypedContractEvent<
    TaskFlaggedEvent.InputTuple,
    TaskFlaggedEvent.OutputTuple,
    TaskFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSubmitted"
  ): TypedContractEvent<
    TaskSubmittedEvent.InputTuple,
    TaskSubmittedEvent.OutputTuple,
    TaskSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskVerified"
  ): TypedContractEvent<
    TaskVerifiedEvent.InputTuple,
    TaskVerifiedEvent.OutputTuple,
    TaskVerifiedEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(uint256,uint256,bool,address)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "ProjectCreated(uint256,string,address,uint256)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "TaskAdded(uint256,uint256,string,uint256)": TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;
    TaskAdded: TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256,address)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskClaimed(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskFlagged(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskFlaggedEvent.InputTuple,
      TaskFlaggedEvent.OutputTuple,
      TaskFlaggedEvent.OutputObject
    >;
    TaskFlagged: TypedContractEvent<
      TaskFlaggedEvent.InputTuple,
      TaskFlaggedEvent.OutputTuple,
      TaskFlaggedEvent.OutputObject
    >;

    "TaskSubmitted(uint256,uint256,address,string,uint256)": TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
    TaskSubmitted: TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;

    "TaskVerified(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;
    TaskVerified: TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;
  };
}
