/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskSplitV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "VERIFIER_ELIGIBILITY_THRESHOLD"
      | "VERIFIER_STAKE"
      | "addPhase"
      | "addTask"
      | "autoVerifyUnvotedTasks"
      | "cancelTask"
      | "claimContributorReward"
      | "claimSponsorRefund"
      | "claimTask"
      | "claimVerifierNFT"
      | "claimVerifierReward"
      | "createProject"
      | "finalizeTaskVoting"
      | "genesisNFT"
      | "getContributorPoints"
      | "getLeaderboard"
      | "getPhase"
      | "getProject"
      | "getProjectCounter"
      | "getProjectDetailed"
      | "getProjectedContributorReward"
      | "getProjectedVerifierReward"
      | "getTask"
      | "getVerifierPoints"
      | "globalEarnings"
      | "hardcodedVerifiers"
      | "hasClaimed"
      | "isEligibleVerifier"
      | "projects"
      | "rewardEarners"
      | "stakeAndVote"
      | "standardNFT"
      | "submitTask"
      | "verifierInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributorRewardClaimed"
      | "PhaseAdded"
      | "PhaseUnlocked"
      | "ProjectCreated"
      | "TaskAdded"
      | "TaskClaimed"
      | "TaskRejected"
      | "TaskSubmitted"
      | "TaskVerified"
      | "TaskVoted"
      | "VerifierNFTClaimed"
      | "VerifierRewardClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "VERIFIER_ELIGIBILITY_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPhase",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addTask",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoVerifyUnvotedTasks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimContributorReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSponsorRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimVerifierNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimVerifierReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [string, BigNumberish, string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTaskVoting",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "genesisNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorPoints",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPhase",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectDetailed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectedContributorReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectedVerifierReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifierPoints",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hardcodedVerifiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEarners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAndVote",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "standardNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitTask",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifierInfo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "VERIFIER_ELIGIBILITY_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPhase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoVerifyUnvotedTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimContributorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSponsorRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimVerifierNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVerifierReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTaskVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "genesisNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContributorPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPhase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectDetailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectedContributorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectedVerifierReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifierPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hardcodedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardEarners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeAndVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "standardNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierInfo",
    data: BytesLike
  ): Result;
}

export namespace ContributorRewardClaimedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    contributor: string,
    amount: bigint,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    contributor: string;
    amount: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseAddedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    phaseId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [projectId: bigint, phaseId: bigint, name: string];
  export interface OutputObject {
    projectId: bigint;
    phaseId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseUnlockedEvent {
  export type InputTuple = [projectId: BigNumberish, phaseId: BigNumberish];
  export type OutputTuple = [projectId: bigint, phaseId: bigint];
  export interface OutputObject {
    projectId: bigint;
    phaseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    name: string,
    sponsor: AddressLike,
    contributorPool: BigNumberish,
    verifierPool: BigNumberish,
    phaseCount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    name: string,
    sponsor: string,
    contributorPool: bigint,
    verifierPool: bigint,
    phaseCount: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    name: string;
    sponsor: string;
    contributorPool: bigint;
    verifierPool: bigint;
    phaseCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAddedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    phaseId: BigNumberish,
    description: string,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    phaseId: bigint,
    description: string,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    phaseId: bigint;
    description: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    claimant: AddressLike
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    claimant: string
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRejectedEvent {
  export type InputTuple = [projectId: BigNumberish, taskId: BigNumberish];
  export type OutputTuple = [projectId: bigint, taskId: bigint];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSubmittedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    contributor: AddressLike,
    proofUrl: string
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    contributor: string,
    proofUrl: string
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    contributor: string;
    proofUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskVerifiedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    contributor: AddressLike,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    contributor: string,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    contributor: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskVotedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    taskId: BigNumberish,
    verifier: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    projectId: bigint,
    taskId: bigint,
    verifier: string,
    approved: boolean
  ];
  export interface OutputObject {
    projectId: bigint;
    taskId: bigint;
    verifier: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierNFTClaimedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRewardClaimedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    verifier: AddressLike,
    amount: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    verifier: string,
    amount: bigint,
    points: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    verifier: string;
    amount: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskSplitV2 extends BaseContract {
  connect(runner?: ContractRunner | null): TaskSplitV2;
  waitForDeployment(): Promise<this>;

  interface: TaskSplitV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VERIFIER_ELIGIBILITY_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_STAKE: TypedContractMethod<[], [bigint], "view">;

  addPhase: TypedContractMethod<
    [projectId: BigNumberish, phaseName: string],
    [void],
    "nonpayable"
  >;

  addTask: TypedContractMethod<
    [
      projectId: BigNumberish,
      phaseId: BigNumberish,
      description: string,
      points: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  autoVerifyUnvotedTasks: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimContributorReward: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimSponsorRefund: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimVerifierNFT: TypedContractMethod<[], [void], "nonpayable">;

  claimVerifierReward: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProject: TypedContractMethod<
    [
      name: string,
      durationDays: BigNumberish,
      phaseNames: string[],
      contributorPoolAmount: BigNumberish,
      verifierPoolAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  finalizeTaskVoting: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  genesisNFT: TypedContractMethod<[], [string], "view">;

  getContributorPoints: TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [],
    [[string[], bigint[]] & { earners: string[]; earnings: bigint[] }],
    "view"
  >;

  getPhase: TypedContractMethod<
    [projectId: BigNumberish, phaseId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        taskCount: bigint;
        verifiedTaskCount: bigint;
        unlocked: boolean;
      }
    ],
    "view"
  >;

  getProject: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        phaseCount: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;

  getProjectCounter: TypedContractMethod<[], [bigint], "view">;

  getProjectDetailed: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        totalVerifiedPoints: bigint;
        totalVerifierPoints: bigint;
        totalPossiblePoints: bigint;
        sponsorRefunded: boolean;
        phaseCount: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;

  getProjectedContributorReward: TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;

  getProjectedVerifierReward: TypedContractMethod<
    [projectId: BigNumberish, verifier: AddressLike],
    [bigint],
    "view"
  >;

  getTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, caller: AddressLike],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        phaseId: bigint;
        description: string;
        points: bigint;
        claimant: string;
        proofUrl: string;
        status: bigint;
        voteCount: bigint;
        claimDeadline: bigint;
        hasVoted: boolean;
      }
    ],
    "view"
  >;

  getVerifierPoints: TypedContractMethod<
    [projectId: BigNumberish, verifier: AddressLike],
    [bigint],
    "view"
  >;

  globalEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  hardcodedVerifiers: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [projectId: BigNumberish, account: AddressLike],
    [
      [boolean, boolean] & {
        contributorClaimed: boolean;
        verifierClaimed: boolean;
      }
    ],
    "view"
  >;

  isEligibleVerifier: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        totalVerifiedPoints: bigint;
        totalVerifierPoints: bigint;
        totalPossiblePoints: bigint;
        sponsorRefunded: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  rewardEarners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  stakeAndVote: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, approved: boolean],
    [void],
    "payable"
  >;

  standardNFT: TypedContractMethod<[], [string], "view">;

  submitTask: TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, proofUrl: string],
    [void],
    "nonpayable"
  >;

  verifierInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalEarned: bigint;
        correctVotes: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VERIFIER_ELIGIBILITY_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPhase"
  ): TypedContractMethod<
    [projectId: BigNumberish, phaseName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTask"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      phaseId: BigNumberish,
      description: string,
      points: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "autoVerifyUnvotedTasks"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimContributorReward"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimSponsorRefund"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimVerifierNFT"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimVerifierReward"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [
      name: string,
      durationDays: BigNumberish,
      phaseNames: string[],
      contributorPoolAmount: BigNumberish,
      verifierPoolAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeTaskVoting"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "genesisNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getContributorPoints"
  ): TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [],
    [[string[], bigint[]] & { earners: string[]; earnings: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPhase"
  ): TypedContractMethod<
    [projectId: BigNumberish, phaseId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        taskCount: bigint;
        verifiedTaskCount: bigint;
        unlocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        phaseCount: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectDetailed"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        totalVerifiedPoints: bigint;
        totalVerifierPoints: bigint;
        totalPossiblePoints: bigint;
        sponsorRefunded: boolean;
        phaseCount: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectedContributorReward"
  ): TypedContractMethod<
    [projectId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectedVerifierReward"
  ): TypedContractMethod<
    [projectId: BigNumberish, verifier: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, caller: AddressLike],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        phaseId: bigint;
        description: string;
        points: bigint;
        claimant: string;
        proofUrl: string;
        status: bigint;
        voteCount: bigint;
        claimDeadline: bigint;
        hasVoted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifierPoints"
  ): TypedContractMethod<
    [projectId: BigNumberish, verifier: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hardcodedVerifiers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [projectId: BigNumberish, account: AddressLike],
    [
      [boolean, boolean] & {
        contributorClaimed: boolean;
        verifierClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEligibleVerifier"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        name: string;
        sponsor: string;
        contributorPool: bigint;
        verifierPool: bigint;
        endTime: bigint;
        totalVerifiedPoints: bigint;
        totalVerifierPoints: bigint;
        totalPossiblePoints: bigint;
        sponsorRefunded: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rewardEarners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "stakeAndVote"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, approved: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "standardNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitTask"
  ): TypedContractMethod<
    [projectId: BigNumberish, taskId: BigNumberish, proofUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifierInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalEarned: bigint;
        correctVotes: bigint;
        totalVotes: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ContributorRewardClaimed"
  ): TypedContractEvent<
    ContributorRewardClaimedEvent.InputTuple,
    ContributorRewardClaimedEvent.OutputTuple,
    ContributorRewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseAdded"
  ): TypedContractEvent<
    PhaseAddedEvent.InputTuple,
    PhaseAddedEvent.OutputTuple,
    PhaseAddedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseUnlocked"
  ): TypedContractEvent<
    PhaseUnlockedEvent.InputTuple,
    PhaseUnlockedEvent.OutputTuple,
    PhaseUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAdded"
  ): TypedContractEvent<
    TaskAddedEvent.InputTuple,
    TaskAddedEvent.OutputTuple,
    TaskAddedEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskRejected"
  ): TypedContractEvent<
    TaskRejectedEvent.InputTuple,
    TaskRejectedEvent.OutputTuple,
    TaskRejectedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSubmitted"
  ): TypedContractEvent<
    TaskSubmittedEvent.InputTuple,
    TaskSubmittedEvent.OutputTuple,
    TaskSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskVerified"
  ): TypedContractEvent<
    TaskVerifiedEvent.InputTuple,
    TaskVerifiedEvent.OutputTuple,
    TaskVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TaskVoted"
  ): TypedContractEvent<
    TaskVotedEvent.InputTuple,
    TaskVotedEvent.OutputTuple,
    TaskVotedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierNFTClaimed"
  ): TypedContractEvent<
    VerifierNFTClaimedEvent.InputTuple,
    VerifierNFTClaimedEvent.OutputTuple,
    VerifierNFTClaimedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRewardClaimed"
  ): TypedContractEvent<
    VerifierRewardClaimedEvent.InputTuple,
    VerifierRewardClaimedEvent.OutputTuple,
    VerifierRewardClaimedEvent.OutputObject
  >;

  filters: {
    "ContributorRewardClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      ContributorRewardClaimedEvent.InputTuple,
      ContributorRewardClaimedEvent.OutputTuple,
      ContributorRewardClaimedEvent.OutputObject
    >;
    ContributorRewardClaimed: TypedContractEvent<
      ContributorRewardClaimedEvent.InputTuple,
      ContributorRewardClaimedEvent.OutputTuple,
      ContributorRewardClaimedEvent.OutputObject
    >;

    "PhaseAdded(uint256,uint256,string)": TypedContractEvent<
      PhaseAddedEvent.InputTuple,
      PhaseAddedEvent.OutputTuple,
      PhaseAddedEvent.OutputObject
    >;
    PhaseAdded: TypedContractEvent<
      PhaseAddedEvent.InputTuple,
      PhaseAddedEvent.OutputTuple,
      PhaseAddedEvent.OutputObject
    >;

    "PhaseUnlocked(uint256,uint256)": TypedContractEvent<
      PhaseUnlockedEvent.InputTuple,
      PhaseUnlockedEvent.OutputTuple,
      PhaseUnlockedEvent.OutputObject
    >;
    PhaseUnlocked: TypedContractEvent<
      PhaseUnlockedEvent.InputTuple,
      PhaseUnlockedEvent.OutputTuple,
      PhaseUnlockedEvent.OutputObject
    >;

    "ProjectCreated(uint256,string,address,uint256,uint256,uint256)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "TaskAdded(uint256,uint256,uint256,string,uint256)": TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;
    TaskAdded: TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;

    "TaskClaimed(uint256,uint256,address)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskRejected(uint256,uint256)": TypedContractEvent<
      TaskRejectedEvent.InputTuple,
      TaskRejectedEvent.OutputTuple,
      TaskRejectedEvent.OutputObject
    >;
    TaskRejected: TypedContractEvent<
      TaskRejectedEvent.InputTuple,
      TaskRejectedEvent.OutputTuple,
      TaskRejectedEvent.OutputObject
    >;

    "TaskSubmitted(uint256,uint256,address,string)": TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;
    TaskSubmitted: TypedContractEvent<
      TaskSubmittedEvent.InputTuple,
      TaskSubmittedEvent.OutputTuple,
      TaskSubmittedEvent.OutputObject
    >;

    "TaskVerified(uint256,uint256,address,uint256)": TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;
    TaskVerified: TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;

    "TaskVoted(uint256,uint256,address,bool)": TypedContractEvent<
      TaskVotedEvent.InputTuple,
      TaskVotedEvent.OutputTuple,
      TaskVotedEvent.OutputObject
    >;
    TaskVoted: TypedContractEvent<
      TaskVotedEvent.InputTuple,
      TaskVotedEvent.OutputTuple,
      TaskVotedEvent.OutputObject
    >;

    "VerifierNFTClaimed(address)": TypedContractEvent<
      VerifierNFTClaimedEvent.InputTuple,
      VerifierNFTClaimedEvent.OutputTuple,
      VerifierNFTClaimedEvent.OutputObject
    >;
    VerifierNFTClaimed: TypedContractEvent<
      VerifierNFTClaimedEvent.InputTuple,
      VerifierNFTClaimedEvent.OutputTuple,
      VerifierNFTClaimedEvent.OutputObject
    >;

    "VerifierRewardClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      VerifierRewardClaimedEvent.InputTuple,
      VerifierRewardClaimedEvent.OutputTuple,
      VerifierRewardClaimedEvent.OutputObject
    >;
    VerifierRewardClaimed: TypedContractEvent<
      VerifierRewardClaimedEvent.InputTuple,
      VerifierRewardClaimedEvent.OutputTuple,
      VerifierRewardClaimedEvent.OutputObject
    >;
  };
}
